language: php

php:
  - 7.3
  - 7.2.4

services:
  - redis-server

before_install:
  - composer self-update
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction
  - composer dump-autoload
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
