language: php

php:
  - 7.2
  - 7.3

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install redis
  - travis_retry composer self-update
  - travis_retry composer install


script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
